### ISSUE TITLE
node bot.js stops midway

### ISSUE THREAD

**Issue by Mettlife** [renesansz/discord-greeter-bot#128]
Hi, I have a problem with node bot.js

When I execute it in powershell it starts doing something and then just stops at `{"message":"mettBOT – (464098033127260163)","level":"info"}`. I can't enter anything else anymore and need to close powershell. The bot also does not react to the '!' command. Anyone know what would fix this for me?

Thanks for the help.

![nodeproblem](https://user-images.githubusercontent.com/19310997/42288806-b5fb5c9e-7fbc-11e8-95e4-4e49260578a1.jpg)

**Comment by sarthaktexas** [comment]
Do don’t use power shell. Use cmd prompt.

**Comment by sarthaktexas** [comment]
Don’t, not do

**Comment by Mettlife** [comment]
Same thing happens when I use cmd.

**Comment by sarthaktexas** [comment]
Please send code.

**Comment by dpadilla1** [comment]
Just kidding I figured my problem out. So its not actually getting stuck, that is supposed to happen and it means your bot is running. The reason my command wasnt working in my Discord server was because my bot didnt have the permission to send messages in the channel it was in. Make sure your bot has the permission to send messages in its role and in the channel.
