### ISSUE TITLE
I can't do one step.

### ISSUE THREAD

**Issue by OuchMyLife** [renesansz/discord-greeter-bot#141]
Whenever I do the install discord.io -- save thing, it gives me an error.

Anybody know how to fix this?

**Comment by Sushomaki** [comment]
First thing, that command you're looking for is: "install discord.io winston --save" so far as I can read, so first step is to make sure that you're using that command correctly.

If you're putting in the command correctly and it looks like the picture, then we're having the same issue, and there's another thread with this problem open, yet THAT thread hasn't been answered to either. Little concerned that it won't get answered, tbh. Like I said, I'm having this problem too.

![image](https://user-images.githubusercontent.com/42757097/44694948-8623fd80-aa3e-11e8-8b4d-c47cd288ae5a.png)

I tried digging into the issue on other sites, but they all say that there's something wrong with the file being corrupted, but that can't be the case because I JUST made this file.
